
version: 2
jobs:
    build:
        docker:
            - image: debian:stretch
        steps:
            - checkout
            - run:
                name: APT_GET UPDATE
                command: apt-get update
            - run:
                name: CXXTEST INSTALLATION
                command: apt-get install -y cxxtest
            - run:
                name: MAKEFILE RUN 
                command: make

