
version: 2
jobs:
    build:
        docker:
            - image: debian:stretch
        steps:
            - checkout
            - run:
                name: APT_GET UPDATE
                command: apt-get update
            - run:
                name: CXXTEST INSTALLATION
                command: apt-get install -y cxxtest
            - run:
                name: COMPILE TEST.H FILE
                command: cxxtestgen --error-printer -o runner.cpp test.h
            - run:
                name:  COMPILE RUNNER.CPP FILE
                command: g++ -o runner -IXXTEST runner.cpp

