
version: 2
jobs:
    build:
        docker:
            - image: debian:stretch
        steps:
            - checkout
            - run:
                name: CXXTEST INSTALLATION
                command: sudo apt install cxxtest
            - run:
                name: MAKEFILE RUN 
                command: make

